In [188]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline
market_cust_data=pd.read_csv("market_cust_data.csv")
# 1. Check the data types of the columns. Get the numeric data into dataframe called numerical and categorical columns in a dataframe called categoricals.
numerical=market_cust_data.select_dtypes(include=np.number)
categoricals=market_cust_data.select_dtypes(include=object)

In [189]:
# 3. Check the multicollinearity between the features.

# Before doing that, to make sure we get the accurate correlation, we try to make sure, we have excluded all the outliers.

def ins_out_var_end_lst(df,out_col_name):
    new_col_lst = list(df.columns)
    new_col_lst.remove(out_col_name)
    new_col_lst.append(out_col_name)
    return df[new_col_lst]
    
def remove_outliers(df,col_name,sig_val):
    if sig_val%3==0:
        iqr = np.percentile(df[col_name],75) - np.percentile(df[col_name],25)
        upper_limit = np.percentile(df[col_name],75) + (sig_val/2)*iqr
        lower_limit = np.percentile(df[col_name],25) - (sig_val/2)*iqr
        return df[(df[col_name]>lower_limit) & (df[col_name]<upper_limit)]
    else:
        return None

In [190]:
#numerical=numerical[numerical['income']>0]
#numerical=remove_outliers(numerical,'customer_lifetime_value',3)
#numerical=remove_outliers(numerical,'monthly_premium_auto',3)

In [191]:
#numerical[numerical['monthly_premium_auto']==0]

In [192]:
numerical=ins_out_var_end_lst(numerical,'total_claim_amount')
correlations_matrix = numerical.corr()
#sns.heatmap(correlations_matrix, annot=True)
#plt.show()

In [ ]:
def filter_high_corr_num_cols(X_num,output_col_name,corr_criteria,dispSelCols=False,heatmap=False):
    selected_cat_cols=[]
    for col in X_num.columns:
        filt_df=X_num[col]
        filt_df_chk=pd.concat([filt_df,y],axis=1)
        filt_df_chk=filt_df_chk[filt_df_chk[output_col_name].isna()==False]
        correlations_matrix = filt_df_chk.corr()
        for col in correlations_matrix.columns:
            if correlations_matrix[col][-1]>=corr_criteria and col !=output_col_name:
                selected_cat_cols.append(col)
        if heatmap==True:
            sns.heatmap(correlations_matrix, annot=True)
            plt.show()
    if dispSelCols==True:
        print(selected_cat_cols)
    return onehot_encoded[selected_cat_cols]

In [193]:
numerical=numerical.drop(['income','months_since_last_claim','months_since_policy_inception','number_of_open_complaints','number_of_policies','effective_to_month'], axis=1)

In [194]:
# 1. X-y split:
from sklearn.preprocessing import MinMaxScaler
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
y = numerical['total_claim_amount']
X = numerical.drop(['total_claim_amount'], axis=1)

In [195]:
# 2. Normalizing data:
transformer = MinMaxScaler().fit(X)
X_normalized = transformer.transform(X)
X_normalized = pd.DataFrame(X_normalized,columns=X.columns)

In [184]:
#X_normalized

In [196]:
X_cat=categoricals[[x for x in list(categoricals.columns) if x not in ['customer','effective_to_date']]]

In [148]:
encoder = OneHotEncoder(drop='first').fit(X_cat)
encoded = encoder.transform(X_cat).toarray()
cols = encoder.get_feature_names_out(input_features=X_cat.columns)
onehot_encoded = pd.DataFrame(encoded, columns=cols)

In [153]:
onehot_encoded

,state_California,state_Nevada,state_Oregon,state_Washington,response_Yes,coverage_Extended,coverage_Premium,education_College,education_Doctor,education_High School or Below,education_Master,employmentstatus_Employed,employmentstatus_Medical Leave,employmentstatus_Retired,employmentstatus_Unemployed,gender_M,location_code_Suburban,location_code_Urban,marital_status_Married,marital_status_Single,policy_type_Personal Auto,policy_type_Special Auto,policy_Corporate L2,policy_Corporate L3,policy_Personal L1,policy_Personal L2,policy_Personal L3,policy_Special L1,policy_Special L2,policy_Special L3,renew_offer_type_Offer2,renew_offer_type_Offer3,renew_offer_type_Offer4,sales_channel_Branch,sales_channel_Call Center,sales_channel_Web,vehicle_class_Luxury Car,vehicle_class_Luxury SUV,vehicle_class_SUV,vehicle_class_Sports Car,vehicle_class_Two-Door Car,vehicle_size_Medsize,vehicle_size_Small,vehicle_type_U
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10272,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
10273,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
10274,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
10275,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
10276,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0

In [152]:
onehot_encoded=onehot_encoded[selected_cat_cols]

KeyError: "['renew_offer_type_Offer1'] not in index"

In [116]:
X = pd.concat([X_normalized, onehot_encoded], axis=1)  # np.concatenate()

In [157]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=76)

In [213]:
def filter_high_corr_cat_cols(X_cat,y,output_col_name,corr_criteria=0.001,dispSelCols=False,heatmap=False):
    encoder = OneHotEncoder().fit(X_cat)
    encoded = encoder.transform(X_cat).toarray()
    cols = encoder.get_feature_names_out(input_features=X_cat.columns)
    onehot_encoded = pd.DataFrame(encoded, columns=cols)
    selected_cat_cols=[]
    for col in X_cat.columns:
        filt_df=onehot_encoded[[x for x in list(onehot_encoded.columns) if x.startswith(col)]]
        filt_df_chk=pd.concat([filt_df,y],axis=1)
        filt_df_chk=filt_df_chk[filt_df_chk[output_col_name].isna()==False]
        correlations_matrix = filt_df_chk.corr()
        for col in correlations_matrix.columns:
            if correlations_matrix[col][-1]>=corr_criteria and col !=output_col_name:
                selected_cat_cols.append(col)
        if heatmap==True:
            sns.heatmap(correlations_matrix, annot=True)
            plt.show()
    if dispSelCols==True:
        print(selected_cat_cols)
    return onehot_encoded[selected_cat_cols]

In [200]:
y

0         292.800000
1         744.924331
2         480.000000
3         484.013411
4         292.800000
            ...
10272     897.600000
10273     273.018929
10274     381.306996
10275     618.288849
10276    1021.719397
Name: total_claim_amount, Length: 10277, dtype: float64

In [212]:
onehot_encoded1=filter_high_corr_cat_cols(X_cat,y,'total_claim_amount',0,True)
X = pd.concat([X_normalized, onehot_encoded1], axis=1)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=76)
lm = linear_model.LinearRegression()
lm.fit(X,y)
print(lm.score(X,y))
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
predictions_test = lm.predict(X_test)
print("r2_score: ",r2_score(y_test, predictions_test))
print("mean absolute error :",mean_absolute_error(y_test, predictions_test))
print("mean square error :",mean_squared_error(y_test,predictions_test))
print("root mean square error :",np.sqrt(mean_squared_error(y_test,predictions_test)))

['state_California', 'state_Nevada', 'state_Oregon', 'state_Washington', 'response_Yes', 'coverage_Extended', 'coverage_Premium', 'education_High School or Below', 'employmentstatus_Disabled', 'employmentstatus_Medical Leave', 'employmentstatus_Retired', 'employmentstatus_Unemployed', 'gender_M', 'location_code_Suburban', 'marital_status_Single', 'policy_type_Personal Auto', 'policy_type_Special Auto', 'policy_type_Personal Auto', 'policy_type_Special Auto', 'policy_Corporate L1', 'policy_Corporate L2', 'policy_Personal L1', 'policy_Special L1', 'policy_Special L3', 'renew_offer_type_Offer1', 'sales_channel_Agent', 'sales_channel_Web', 'vehicle_class_Luxury Car', 'vehicle_class_Luxury SUV', 'vehicle_class_SUV', 'vehicle_class_Sports Car', 'vehicle_size_Small', 'vehicle_type_A']
0.7179594991056655
r2_score:  0.7090146351315654
mean absolute error : 114.00698710457004
mean square error : 24395.836859126186
root mean square error : 156.19166706046192

In [199]:
X_normalized

       customer_lifetime_value  monthly_premium_auto
0                     0.035752              0.000000
1                     0.004059              0.012658
2                     0.160264              0.164557
3                     0.250953              0.151899
4                     0.034966              0.000000
...                        ...                   ...
10272                 0.212833              0.531646
10273                 0.041281              0.016878
10274                 0.270122              0.590717
10275                 0.123717              0.409283
10276                 0.060907              0.168776

[10277 rows x 2 columns]

In [151]:
selected_cat_cols

['coverage_Extended',
 'coverage_Premium',
 'education_High School or Below',
 'employmentstatus_Unemployed',
 'location_code_Suburban',
 'marital_status_Single',
 'renew_offer_type_Offer1',
 'vehicle_class_Luxury Car',
 'vehicle_class_Luxury SUV',
 'vehicle_class_SUV']

In [119]:
#df2=pd.concat([onehot_encoded,y],axis=1)
#df2=df2[df2['total_claim_amount'].isna()==False]

In [120]:
# let's merge all this information together into a single dataset with all features, now numerical
#X = pd.concat([X_normalized, onehot_encoded], axis=1)  # np.concatenate()

In [163]:
X

,customer_lifetime_value,monthly_premium_auto,coverage_Extended,coverage_Premium,education_High School or Below,employmentstatus_Unemployed,location_code_Suburban,marital_status_Single,renew_offer_type_Offer1,vehicle_class_Luxury Car,vehicle_class_Luxury SUV,vehicle_class_SUV
0,0.035752,0.000000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.004059,0.012658,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
2,0.160264,0.164557,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
3,0.250953,0.151899,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
4,0.034966,0.000000,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
10272,0.212833,0.531646,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0
10273,0.041281,0.016878,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10274,0.270122,0.590717,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
10275,0.123717,0.409283,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
10276,0.060907,0.168776,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0

In [161]:
# Fitting the Linear regression model
lm = linear_model.LinearRegression()
lm.fit(X,y)
print(lm.score(X,y))

0.7150842635365855

In [162]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
predictions_test = lm.predict(X_test)
print("r2_score: ",r2_score(y_test, predictions_test))
print("mean absolute error :",mean_absolute_error(y_test, predictions_test))
print("mean square error :",mean_squared_error(y_test,predictions_test))
print("root mean square error :",np.sqrt(mean_squared_error(y_test,predictions_test)))

ValueError: X has 46 features, but LinearRegression is expecting 12 features as input.

In [25]:
#lm = linear_model.LinearRegression()
#lm.fit(X,y)
#print(lm.score(X,y))
#y_pred = lm.predict(X)
#print(mean_squared_error(y_pred,y))

0.4096637545770393
37868.95298463951